# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 60
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - script: |
      conda update -n base -c defaults conda -y
      conda create --yes --name pdal -c conda-forge pdal pytest numpy compilers scikit-build
    displayName: 'Dependencies'
  - script: |
      source activate pdal
      echo $CONDA_PREFIX
      echo $CONDA_DEFAULT_ENV
      pip install  .
      pdal --drivers
    displayName: 'System install'
  - script: |
      source activate pdal
      pip install  -e .
      SKPATH=$(python -c "import skbuild; print (skbuild.constants.SKBUILD_DIR())")/cmake-build
      export PDAL_DRIVER_PATH=$SKPATH
      $SKPATH/pdal_filters_python_test
      $SKPATH/pdal_io_numpy_test
      py.test
    displayName: 'Local test'
