# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.14
  timeoutInMinutes: 360
  steps:
  - script: |
      echo "Removing homebrew from Azure to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew
    displayName: Remove homebrew
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH

  - script: |
      ECHO ON
      source activate base
      conda update -n base -c defaults conda -y
      conda create --yes --quiet --name pdal
    displayName: Create conda environment

  - script: |
      ECHO ON
      source activate pdal
      conda install --yes --quiet --name pdal -c conda-forge scikit-build pdal pytest numpy conda-forge-ci-setup=2 -y
    displayName: Install PDAL
  - script: |
      source activate pdal
      export CI=azure
      source run_conda_forge_build_setup
    env: {
      OSX_FORCE_SDK_DOWNLOAD: "1"
    }
    displayName: Configure OSX SDK
  - script: |
      source activate pdal
      pip install  .
    displayName: 'System install'
  - script: |
      source activate pdal
      which pytest
      pytest
      pip install  -e .
      SKPATH=$(python -c "import skbuild; print (skbuild.constants.SKBUILD_DIR())")/cmake-build
      export PDAL_DRIVER_PATH=$SKPATH
      $SKPATH/pdal_filters_python_test
      $SKPATH/pdal_io_numpy_test
      pdal --version
      pdal --drivers
    displayName: 'Local test'

