name: testenv
channels:
  - conda-forge
dependencies:
  - scikit-build-core >=1.0
  - numpy >=1.24
  - compilers
  - ninja
  - pybind11 >=2.12
  - libpdal-core
  - pytest >=8
  - meshio >=5.3
  - geopandas
  - uv
