version: 1.0.{build}

os: Visual Studio 2015

platform: x64


matrix:
  fast_finish: true

# Should speed up repository cloning
#
shallow_clone: true
clone_depth: 5

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

cache:
    C:\Miniconda3-x64\pkgs -> appveyor.yml

install:
 - call scripts\\appveyor\\config.cmd

build_script:
 - call scripts\\appveyor\\build.cmd

test_script:
 - call scripts\\appveyor\\test.cmd
 -
